"""empty message

Revision ID: 2be015b4e01f
Revises: 
Create Date: 2018-03-28 21:14:14.894452

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2be015b4e01f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donorinfo', sa.Column('org_name', sa.String(length=300), nullable=True))
    op.add_column('projectinfo', sa.Column('org_name', sa.String(length=300), nullable=True))
    op.alter_column('sampleinfo', 'inv_id',
               existing_type=mysql.VARCHAR(length=500),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sampleinfo', 'inv_id',
               existing_type=mysql.VARCHAR(length=500),
               nullable=False)
    op.drop_column('projectinfo', 'org_name')
    op.drop_column('donorinfo', 'org_name')
    # ### end Alembic commands ###
