"""empty message

Revision ID: 67f482af5a06
Revises: 
Create Date: 2018-04-20 20:17:42.023851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67f482af5a06'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catecode',
    sa.Column('cate_name', sa.String(length=100), nullable=False),
    sa.Column('cate_level', sa.Integer(), nullable=True),
    sa.Column('cate_mark', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('cate_name')
    )
    op.create_table('donorinfo',
    sa.Column('don_id', sa.String(length=500), nullable=False),
    sa.Column('col_obj', sa.String(length=1000), nullable=True),
    sa.Column('date_of_bir', sa.Integer(), nullable=True),
    sa.Column('eth_gro', sa.String(length=1000), nullable=True),
    sa.Column('nativ_pla', sa.String(length=1000), nullable=True),
    sa.Column('bir_pla', sa.String(length=1000), nullable=True),
    sa.Column('nation', sa.String(length=1000), nullable=True),
    sa.Column('occup', sa.String(length=1000), nullable=True),
    sa.Column('edu_lev', sa.String(length=1000), nullable=True),
    sa.Column('mari_sta', sa.String(length=1000), nullable=True),
    sa.Column('donate_way', sa.String(length=1000), nullable=True),
    sa.Column('dise_name', sa.String(length=1000), nullable=True),
    sa.Column('dise_id', sa.String(length=1000), nullable=True),
    sa.Column('dig_desc', sa.Text(), nullable=True),
    sa.Column('dise_his', sa.Text(), nullable=True),
    sa.Column('exa_rec', sa.Text(), nullable=True),
    sa.Column('inter_rec', sa.String(length=1000), nullable=True),
    sa.Column('media_rec', sa.String(length=1000), nullable=True),
    sa.Column('medi_rep', sa.String(length=1000), nullable=True),
    sa.Column('fam_his', sa.String(length=1000), nullable=True),
    sa.Column('org_name', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('don_id')
    )
    op.create_table('orginfo',
    sa.Column('org_name', sa.String(length=500), nullable=False),
    sa.Column('jur_per_name', sa.String(length=1000), nullable=True),
    sa.Column('jur_per_id', sa.String(length=1000), nullable=True),
    sa.Column('jur_per_type', sa.String(length=1000), nullable=True),
    sa.Column('org_intro', sa.Text(), nullable=True),
    sa.Column('use_agr', sa.String(length=1000), nullable=True),
    sa.Column('share_rule', sa.String(length=1000), nullable=True),
    sa.Column('adr', sa.Text(), nullable=True),
    sa.Column('post_code', sa.String(length=1000), nullable=True),
    sa.Column('manager_name', sa.String(length=1000), nullable=True),
    sa.Column('tel', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('org_name')
    )
    op.create_table('projectinfo',
    sa.Column('prj_name', sa.String(length=1000), nullable=True),
    sa.Column('prj_id', sa.String(length=500), nullable=False),
    sa.Column('prj_level', sa.String(length=1000), nullable=True),
    sa.Column('spon_org', sa.String(length=1000), nullable=True),
    sa.Column('in_level', sa.String(length=1000), nullable=True),
    sa.Column('keyword', sa.String(length=1000), nullable=True),
    sa.Column('aim', sa.String(length=1000), nullable=True),
    sa.Column('mtd', sa.String(length=1000), nullable=True),
    sa.Column('total_amt', sa.Integer(), nullable=True),
    sa.Column('be_end_time', sa.String(length=1000), nullable=True),
    sa.Column('org_name', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('prj_id')
    )
    op.create_table('sampleinfo',
    sa.Column('sam_uni_id', sa.String(length=300), nullable=False),
    sa.Column('inv_id', sa.String(length=500), nullable=True),
    sa.Column('sam_cate_name', sa.String(length=500), nullable=True),
    sa.Column('ent_date', sa.Date(), nullable=True),
    sa.Column('stor_meth', sa.String(length=500), nullable=True),
    sa.Column('parent_id', sa.String(length=500), nullable=True),
    sa.Column('batch_count', sa.Integer(), nullable=True),
    sa.Column('sam_qty', sa.Integer(), nullable=True),
    sa.Column('unit_amou', sa.String(length=500), nullable=True),
    sa.Column('consent', sa.Boolean(), nullable=True),
    sa.Column('sam_title', sa.String(length=500), nullable=True),
    sa.Column('sam_desc', sa.Text(), nullable=True),
    sa.Column('keyword', sa.String(length=500), nullable=True),
    sa.Column('sam_uses', sa.String(length=500), nullable=True),
    sa.Column('acqui_pos', sa.String(length=500), nullable=True),
    sa.Column('s_pre_c', sa.String(length=500), nullable=True),
    sa.Column('acqui_mot', sa.String(length=500), nullable=True),
    sa.Column('acqui_time', sa.Date(), nullable=True),
    sa.Column('acqui_plan', sa.Text(), nullable=True),
    sa.Column('acqui_org', sa.String(length=500), nullable=True),
    sa.Column('acqui_assis', sa.String(length=500), nullable=True),
    sa.Column('org_name', sa.String(length=500), nullable=True),
    sa.Column('don_id', sa.String(length=500), nullable=True),
    sa.Column('proj_id', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('sam_uni_id')
    )
    op.create_table('userinfo',
    sa.Column('user_account', sa.String(length=300), nullable=False),
    sa.Column('user_psd', sa.String(length=300), nullable=True),
    sa.Column('user_lv', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('user_account')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userinfo')
    op.drop_table('sampleinfo')
    op.drop_table('projectinfo')
    op.drop_table('orginfo')
    op.drop_table('donorinfo')
    op.drop_table('catecode')
    # ### end Alembic commands ###
